version: '3.5'

services:
  zookeeper-ccc:
    image: localbuild/cp-zookeeper-tc:7.4.1
    hostname: zookeeper-ccc
    container_name: zookeeper-ccc
    networks:
      - n1
    ports:
      - "2188:2188"
    volumes:
      - ./config/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf   
    environment:
      ZOOKEEPER_SERVER_ID: 4
      ZOOKEEPER_CLIENT_PORT: 2188
      ZOOKEEPER_SERVERS: zookeeper-ccc:2888:3888
      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      ZOOKEEPER_JAAS_LOGIN_RENEW: 3600000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf      

  broker-ccc:
    image: localbuild/cp-server-tc:7.4.1
    hostname: broker-ccc
    container_name: broker-ccc
    networks:
      - n1
    ports:
      - "9098:9098"
      - "8098:8098"
    volumes:
      - ./config:/etc/kafka/demo
    environment:
      KAFKA_BROKER_ID: 8
      KAFKA_BROKER_RACK: 'metrics'
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-ccc:19098,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP}:9098
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:SASL_PLAINTEXT,LISTENER_DOCKER_EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-ccc:19098,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP}:9098
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-ccc:2188'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      KAFKA_CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
      KAFKA_CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                          username="admin" \
                                                          password="Abc@12314455";
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/demo/kafka_jaas.conf"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN                                                                     
      KAFKA_JMX_PORT: 8098
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-ccc

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.4.1
    hostname: control-center
    container_name: control-center
    networks:
      - n1
    depends_on:
      - zookeeper-ccc
      - broker-ccc
    ports:
      - "9021:9021"
    volumes:
      - ./config:/etc/controlcenter/config
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker-ccc:19098
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_KAFKA_METRICS_BOOTSTRAP_SERVERS: broker-ccc:19098
      CONTROL_CENTER_CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      
      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                          username="admin" \
                                                          password="Abc@12314455";
      CONTROL_CENTER_REST_AUTHENTICATION_REALM: c3
      CONTROL_CENTER_REST_AUTHENTICATION_METHOD: BASIC
      CONTROL_CENTER_REST_AUTHENTICATION_ROLES: administrator,operator
      CONTROL_CENTER_AUTH_RESTRICTED_ROLES: operator
      CONTROL_CENTER_AUTH_SESSION_EXPIRATION_MS: 600000
      CONTROL_CENTER_OPTS: "-Djava.security.auth.login.config=/etc/controlcenter/config/propertyfile.jaas"
      PORT: 9021

networks:
  n1:
